"""
Django settings for M6_AE3_ind project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u2dis$vcm1yq3r&zn5yxnjbws@2cb!(!+#82+ia$b0%wei83&a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

"""
La variable LOGIN_REDIRECT_URL se utiliza para especificar a qué URL será redirigido al 
usuario después de que haya iniciado correctamente su sesión en la aplicación. Por defecto, 
esta variable está configurada en /accounts/profile/, pero puede ser cambiada para redirigir a cualquier URL deseada.

La variable LOGOUT_REDIRECT_URL se utiliza para especificar la URL a la que será redirigido 
el usuario después de que haya cerrado satisfactoriamente su sesión en la aplicación. 
Por defecto, esta variable está configurada en /accounts/login/, pero se puede cambiar para redirigir a cualquier URL deseada.

La constante LOGIN_URL se utiliza para especificar la URL de inicio de sesión que se usará 
cuando el usuario no está autenticado y necesita iniciar sesión para acceder a una página protegida. 
Por defecto, esta constante está configurada en /accounts/login/, pero se puede cambiar para utilizar una URL personalizada.

La constante LOGOUT_URL se utiliza para especificar la URL de cierre de sesión que se utiliza 
cuando un usuario desea cerrar sesión en la aplicación. Por defecto, esta constante está configurada en /accounts/logout/, 
pero se puede cambiar para utilizar una URL personalizada.
"""
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = 'login/'
LOGOUT_URL = 'logout/'

# Application definition

INSTALLED_APPS = [

    'aplicacion_3',
    'crispy_forms',
    'django.contrib.admin',
    'django.contrib.auth',   
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'M6_AE5_individual.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'M6_AE5_individual.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
